name: CI/CD

on:
  push:
    branches:
      - main

env:
  POSTGRES_USER: api-platform
  POSTGRES_PASSWORD: 0000
  POSTGRES_DB: api
  POSTGRES_VERSION: 13
  HTTP_PORT: 80
  HTTPS_PORT: 443
  HTTP3_PORT: 443
  VITE_PORT: 3000
  SERVER_NAME: localhost
  TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  CADDY_MERCURE_URL: http://caddy/.well-known/mercure
  CADDY_MERCURE_JWT_SECRET: 0000
  PHP_VERSION: 8.1
  CADDY_VERSION: 2
  APP_ENV: prod
  SYMFONY_PHPUNIT_VERSION: 9
  VPS_IP: 51.178.42.231
  VPS_USER: debian

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Build Backend
        run: |
          docker build -t api-platform-backend -f api/Dockerfile .

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: your-docker-username/api-platform-backend:${{ env.APP_ENV }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker pull your-docker-username/api-platform-backend:${{ env.APP_ENV }}
            docker stop api-platform-backend
            docker rm api-platform-backend
            docker run -d --name api-platform-backend -p 8080:80 api-platform-backend:${{ env.APP_ENV }}

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            docker stop api-platform-backend
            docker rm api-platform-backend
            docker run -d --name api-platform-backend -p 8080:80 api-platform-backend:prod
