name: CI/CD for API Platform

on:
  push:
    branches:
      - main

env:
  POSTGRES_USER: api-platform
  POSTGRES_PASSWORD: 0000
  POSTGRES_DB: api
  POSTGRES_VERSION: 13
  HTTP_PORT: 80
  HTTPS_PORT: 443
  HTTP3_PORT: 443
  VITE_PORT: 5173
  SECRET: "secret_token"
  BASE_URL: "http://localhost"
  VITE_BACKEND_URL: https://localhost
  SERVER_NAME: localhost
  TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  CADDY_MERCURE_URL: http://caddy/.well-known/mercure
  CADDY_MERCURE_JWT_SECRET: 0000
  PHP_VERSION: 8.1
  CADDY_VERSION: 2
  APP_ENV: dev
  SYMFONY_PHPUNIT_VERSION: 9
  # API Platform distribution
  TRUSTED_PROXIES: 127.0.0.1
  TRUSTED_HOSTS: ^localhost$

  ###> symfony/framework-bundle ###
  APP_ENV: dev
  APP_SECRET: !ChangeMe!
  ###< symfony/framework-bundle ###

  ###> doctrine/doctrine-bundle ###
  # Format described at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#connecting-using-a-url
  # IMPORTANT: You MUST configure your server version, either here or in config/packages/doctrine.yaml
  #
  # DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
  # DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=5.7"
  DATABASE_URL: "postgresql://api-platform:!ChangeMe!@127.0.0.1:5432/api?serverVersion=13&charset=utf8"
  ###< doctrine/doctrine-bundle ###

  ###> nelmio/cors-bundle ###
  CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
  ###< nelmio/cors-bundle ###

  ###> symfony/mercure-bundle ###
  # See https://symfony.com/doc/current/mercure.html#configuration
  # The URL of the Mercure hub, used by the app to publish updates (can be a local URL)
  MERCURE_URL: http://caddy/.well-known/mercure
  # The public URL of the Mercure hub, used by the browser to connect
  MERCURE_PUBLIC_URL: https://localhost/.well-known/mercure
  # The secret used to sign the JWTs
  MERCURE_JWT_SECRET: "!ChangeMe!"
  ###< symfony/mercure-bundle ###

  ###> lexik/jwt-authentication-bundle ###
  JWT_SECRET_KEY: %kernel.project_dir%/config/jwt/private.pem
  JWT_PUBLIC_KEY: %kernel.project_dir%/config/jwt/public.pem
  JWT_PASSPHRASE: 870888198df3de87ae443407a73f5ad3
  ###< lexik/jwt-authentication-bundle ###

  ###> symfony/mailer ###
  # MAILER_DSN: null://null
  MAILER_FROM: esgi-challenge@webdealer.fr
  MAILER_PASSWORD: azerty123
  MAILER_SERVER: ssl0.ovh.net
  MAILER_PORT: 465
  MAILER_DSN: smtp://${MAILER_FROM}:${MAILER_PASSWORD}@${MAILER_SERVER}:${MAILER_PORT}
  ###< symfony/mailer ###

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Frontend dependencies
        working-directory: front/
        run: |
          npm install

      - name: Build Frontend
        working-directory: front/
        run: |
          npm run build

      - name: Build Backend
        working-directory: api/
        run: |
          docker-compose build
