name: CI/CD for API Platform and VueJS

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Env file
        run: |
          echo "VITE_PORT=\"5173\"" >> ./api/.env

          echo "APP_ENV=\"${{secrets.APP_ENV}}\"" >> ./api/.env
          echo "APP_SECRET=\"${{secrets.APP_SECRET}}\"" >> ./api/.env

          echo "BASE_URL=\"${{secrets.BASE_URL}}\"" >> ./front/.env

          echo "CORS_ALLOW_ORIGIN=\"${{secrets.CORS_ALLOW_ORIGIN}}\"" >> ./api/.env
          echo "DATABASE_URL=\"${{secrets.DATABASE_URL}}\"" >> ./api/.env
          echo "JWT_PASSPHRASE=\"${{secrets.JWT_PASSPHRASE}}\"" >> ./api/.env
          echo "JWT_PUBLIC_KEY=\"${{secrets.JWT_PUBLIC_KEY}}\"" >> ./api/.env
          echo "JWT_SECRET_KEY=\"${{secrets.JWT_SECRET_KEY}}\"" >> ./api/.env
          echo "MAILER_DSN=\"${{secrets.MAILER_DSN}}\"" >> ./api/.env
          echo "MAILER_FROM=\"${{secrets.MAILER_FROM}}\"" >> ./api/.env
          echo "MAILER_PASSWORD=\"${{secrets.MAILER_PASSWORD}}\"" >> ./api/.env
          echo "MAILER_PORT=\"${{secrets.MAILER_PORT}}\"" >> ./api/.env
          echo "MAILER_SERVER=\"${{secrets.MAILER_SERVER}}\"" >> ./api/.env
          echo "MERCURE_JWT_SECRET=\"${{secrets.MERCURE_JWT_SECRET}}\"" >> ./api/.env
          echo "MERCURE_PUBLIC_URL=\"${{secrets.MERCURE_PUBLIC_URL}}\"" >> ./api/.env
          echo "MERCURE_URL=\"${{secrets.MERCURE_URL}}\"" >> ./api/.env
          echo "TRUSTED_HOSTS=\"${{secrets.TRUSTED_HOSTS}}\"" >> ./api/.env
          echo "TRUSTED_PROXIES=\"${{secrets.TRUSTED_PROXIES}}\"" >> ./api/.env

          echo "VITE_BACKEND_URL=\"${{secrets.VITE_BACKEND_URL}}\"" >> ./front/.env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Backend
        working-directory: api/
        run: |
          docker-compose build --no-cache

      - name: Start Backend
        run: |
          docker-compose up -d

      - name: Install Frontend dependencies
        run: |
          docker-compose exec -d front npm install

      - name: Build Frontend for production
        run: |
          docker-compose exec -d front npm run build

      - name: Start Frontend for production
        run: |
          docker-compose exec -d front npm run preview

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: api
          push: true
          tags: thepiotrow/api-platform-backend:latest

      - name: Deploy to OVH VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # uses secrets stored in the Secrets tab
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: sh ~/ci/deploy.sh
