name: CI/CD for API Platform

on:
  push:
    branches:
      - main

env:
  POSTGRES_USER: api-platform
  POSTGRES_PASSWORD: 0000
  POSTGRES_DB: api
  POSTGRES_VERSION: 13
  HTTP_PORT: 80
  HTTPS_PORT: 443
  HTTP3_PORT: 443
  VITE_PORT: 5173
  SECRET: "secret_token"
  BASE_URL: "http://localhost"
  VITE_BACKEND_URL: https://localhost
  SERVER_NAME: localhost
  TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  CADDY_MERCURE_URL: http://caddy/.well-known/mercure
  CADDY_MERCURE_JWT_SECRET: 0000
  PHP_VERSION: 8.1
  CADDY_VERSION: 2
  APP_ENV: prod
  SYMFONY_PHPUNIT_VERSION: 9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Frontend dependencies
        working-directory: front/
        run: |
          npm install

      - name: Build Frontend
        working-directory: front/
        run: |
          npm run build

      - name: Build Backend
        working-directory: api/
        run: |
          docker-compose build \
          -e VITE_PORT=${vars.VITE_PORT} \
          -e VITE_BACKEND_URL=${vars.VITE_BACKEND_URL} \
          -e BASE_URL=${vars.BASE_URL} \
          -e TRUSTED_PROXIES=${vars.TRUSTED_PROXIES} \
          -e TRUSTED_HOSTS=${vars.TRUSTED_HOSTS} \
          -e APP_ENV=${vars.APP_ENV} \
          -e APP_SECRET=${vars.APP_SECRET} \
          -e DATABASE_URL=${vars.DATABASE_URL} \
          -e CORS_ALLOW_ORIGIN=${vars.CORS_ALLOW_ORIGIN} \
          -e MERCURE_URL=${vars.MERCURE_URL} \
          -e MERCURE_PUBLIC_URL=${vars.MERCURE_PUBLIC_URL} \
          -e MERCURE_JWT_SECRET=${vars.MERCURE_JWT_SECRET} \
          -e JWT_SECRET_KEY=${vars.JWT_SECRET_KEY} \
          -e JWT_PUBLIC_KEY=${vars.JWT_PUBLIC_KEY} \
          -e JWT_PASSPHRASE=${vars.JWT_PASSPHRASE} \
          -e MAILER_FROM=${vars.MAILER_FROM} \
          -e MAILER_PASSWORD=${vars.MAILER_PASSWORD} \
          -e MAILER_SERVER=${vars.MAILER_SERVER} \
          -e MAILER_PORT=${vars.MAILER_PORT} \
          -e MAILER_DSN=${vars.MAILER_DSN}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: thepiotrow/api-platform-backend:${{ env.APP_ENV }}

      - name: Deploy to OVH VPS
        uses: ovh/actions/server-deploy@main
        with:
          access_key: ${{ secrets.OVH_ACCESS_KEY }}
          secret_key: ${{ secrets.OVH_SECRET_KEY }}
          endpoint: ovh-eu
          server_name: my-vps
          command: |
            scp api/docker-compose.yml my-vps:/root/api-platform
            ssh my-vps "cd ~/api-platform && docker-compose up -d"
