name: CI/CD for API Platform

on:
  push:
    branches:
      - main

env:
  POSTGRES_USER: api-platform
  POSTGRES_PASSWORD: !ChangeMe!
  POSTGRES_DB: api
  POSTGRES_VERSION: 13
  HTTP_PORT: 80
  HTTPS_PORT: 443
  HTTP3_PORT: 443
  VITE_PORT: 3000
  SERVER_NAME: localhost
  TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  CADDY_MERCURE_URL: http://caddy/.well-known/mercure
  CADDY_MERCURE_JWT_SECRET: !ChangeMe!
  PHP_VERSION: 8.1
  CADDY_VERSION: 2
  APP_ENV: prod
  SYMFONY_PHPUNIT_VERSION: 9

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install Frontend dependencies
      working-directory: front/
      run: |
        npm install

    - name: Build Frontend
      working-directory: front/
      run: |
        npm run build

    - name: Build Backend
      working-directory: api/
      run: |
        docker-compose build

    - name: Push to Docker Hub
      working-directory: api/
      uses: docker/build-push-action@v2
      with:
        context: api
        push: true
        tags: thepiotrow/api-platform-backend:${{ env.APP_ENV }}
